twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        cart_manager: '@App\User\UserCartManager'
    form_themes: ['bootstrap_5_horizontal_layout.html.twig']

when@test:
    twig:
        strict_variables: true
